[env:atmega8]
platform = atmelavr
board = atmega8
board_build.f_cpu = 16000000UL

board_fuses.lfuse = 0xE4
board_fuses.hfuse = 0xD9

; Override the default upload command to use my custom AVR programmer tool
; Wir nutzen den integrierten AVRDUDE-Standard von PlatformIO
upload_protocol = custom
upload_port = COM3

; Das stk500v2-Protokoll ist der native Modus des mySmartUSB light
upload_flags =
    -C
    ${platformio.packages_dir}/tool-avrdude/avrdude.conf
    -p
    atmega8
    -P
    $UPLOAD_PORT
    -c
    stk500v2
    -F  ; Ignoriert den efuse-Fehler des ATmega8
    -u  ; Deaktiviert den Safemode-Rücklese-Check

upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i